jobs:
- name: build-test-backend
  public: true
  plan: 
  - get: repository
    trigger: true
    version: every
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sh
        args:
        - -exc
        - |
           echo "hello world"
#  - task: build-test
#    file: repository/concourse/build-and-test/build-and-test.yml

- name: bump-patch
  public: true
  plan: 
  - get: version
  - get: repository
    passed: [build-test-backend]
    trigger: true
  - task: version
    file: repository/concourse/version/version.yml

#  - put: version
#    params: {file: version/version}
#    on_success:
#      put: repository
#      params:
#        path: repository
#        status: success        
#  - put: repository
#    params:
#      path: repository
#      status: success
#      merge:
#        method: squash   


# Resources and resource types
#############################################################################################################
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
    tag: v31

- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
    tag: 2.7.2-4

resources:
- name: repository
  type: pull-request
  source:
    access_token: {{concourse-pull-request-token}}
    private_key: {{concourse-token}}
    repo: Sharor/concourse-tmp-pullreq-testing
    base: master
    uri: https://github.com/Sharor/concourse-tmp-pullreq-testing.git
    private_key: {{concourse-token}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.0
    uri: git@github.com:Sharor/MuninnConfigs.git
    branch: version
    file: version
    private_key: {{concourse-token}}

#- name: release-docker-image
#  type: docker-image
#  source:
#    username: {{docker-hub-username}}
#    password: {{docker-hub-password}}
#    repository: {{docker-repository}}